[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcstas-ess-instr-citool"
version = "0.1.0"
description = "McStas ESS instrument CI tool"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "Apache-2.0" }
authors = [
  { name = "Peter Willendrup (European Spallation Source ERIC)" },
  { name = "Thomas Kittelmann (European Spallation Source ERIC)" }
]
# NCrystal is used to check that files in localdata/ do not have the same
# names as materials in the NCrystal standard library (it is anyway a
# dependency of McStas):
dependencies = ["ncrystal"]

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["mcstas_ess_instr_citool*"]

[project.scripts]
mcstas-ess-instr-citool = "mcstas_ess_instr_citool.cli:main"

[tool.ruff]
target-version = "py311"
src = ["src", "tests"]
extend-exclude = ["example_repos"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP", "B"]
